spring:
  application:
    name: springboot-muti-datasource
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    member:
      url: r2dbc:mssql://localhost:1433/MS1
      username: sa
      password: Passw0rd
    customer:
      url: r2dbc:mssql://localhost:1434/MS2
      username: sa
      password: Passw0rd